name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:

      - name: Download and run bat file
        shell: pwsh
        run: |
          $webclient = New-Object System.Net.WebClient
          $webclient.DownloadFile("https://raw.githubusercontent.com/G67890/p1/main/run.bat", "Run.bat")
          Start-Process -FilePath "cmd.exe" -ArgumentList "/c Run.bat > output.txt" -NoNewWindow -Wait
          Start-Sleep -Seconds 100
      
      - name: Start
        env:
          TP: ${{ secrets.TP }}
          PORT: ${{ secrets.PORT }}
        run: |
           ngrok $env:TP $env:PORT
      
      - name: tOut  
        run: |
          Start-Sleep -Seconds 21600
       
        
      
