name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:

      - name: Install
        
        run: curl -O https://raw.githubusercontent.com/G67890/Nw/main/.github/workflows/main.yml
        
         
      - name: timeOut  
        run: sleep 21009
       
        
      
